detectors:
  startout:
    type: cpu
  coral_tpu:
    type: edgetpu

ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 2
  hwaccel_args: preset-rpi-64-h264

camera:
  house:
    enabled: True
    ffmpeg:
      inputs:
        - path: somethigsn
          roles:
            - detect
            - record
            - restream
