detectors:
  coral_tpu:
    type: edgetpu
    device: usb

mqtt:
  host: pee-house.local

ffmpeg:
  global_args: -hide_banner -loglevel error -threads 2
  hwaccel_args: preset-rpi-64-h264

detect:
  width: 1920
  height: 1080
  fps: 5

record:
  enabled: True

cameras:
  house:
    enabled: True
    ffmpeg:
      inputs:
        - path: "/dev/video0"
          roles:
            - detect
            - record
      input_args: -f v4l2 -c:v h264_v4l2m2m -use_wallclock_as_timestamps 1 -fflags +genpts+discardcorrupt

objects:
  track:
    - cat

motion:
  mask:
    - 568,1080,652,331,996,333,1920,1080,1920,303,1920,0,0,0,0,1080
  threshold: 10
  contour_area: 20

snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
