detectors:
  coral_tpu:
    type: edgetpu
    device: usb

mqtt:
  host: pee-house.local

ffmpeg:
  global_args: -hide_banner -loglevel debug -threads 2
  hwaccel_args: preset-rpi-64-h264

detect:
  width: 640
  height: 480
  fps: 5

record:
  enabled: True

cameras:
  house:
    enabled: True
    ffmpeg:
      inputs:
        - path: "/dev/video0"
          roles:
            - detect
            - record
      input_args: -r 30 -f v4l2 -c:v h264_v4l2m2m -use_wallclock_as_timestamps 1 -s:v 640x480 -fflags +genpts+discardcorrupt

objects:
  track:
    - cat

motion:
  mask:
    - 330,0,640,0,640,480,332,140,185,134,152,480,0,480,0,0
  threshold: 10
  contour_area: 20

snapshots:
  enabled: True
  bounding_box: True
